import sys
import json
import importlib.util
from pathlib import Path

# Add backend to path so we can import
sys.path.append(str(Path(__file__).resolve().parent / "backend"))

spec = importlib.util.spec_from_file_location("content_agent", str(Path(__file__).resolve().parent / "backend/content-agent/content_agent.py"))
content_agent_module = importlib.util.module_from_spec(spec)
spec.loader.exec_module(content_agent_module)
ContentAgent = content_agent_module.ContentAgent

def run_tests():
    agent = ContentAgent(None)
    
    print("==================================================")
    print("TEST 1: THE OLD ARCHITECTURE (STATIC FALLBACK)")
    print("==================================================")
    # This is a static tag that relies on manual templates
    result_static = agent.generate(
        subtopic="Plane Mirrors",
        misconception_tag="image_real_confusion",
        attempt=2,
        question_text="If you stand 2m in front of a plane mirror, where is the image formed?",
        student_answer="It is formed on a screen 2m behind the mirror.",
    )
    
    print(f"SVG Component Chosen: {result_static['svg_component']}")
    print(f"Animation Parameters: {result_static['animation_parameters']} (Should be None)")
    print(f"Explanation: {result_static['explanation'][:100]}...\n")


    print("==================================================")
    print("TEST 2: THE NEW REGENERATIVE ARCHITECTURE (DYNAMIC)")
    print("==================================================")
    # This is a dynamic tag that triggers the LLM math generation
    result_dynamic = agent.generate(
        subtopic="Spherical Mirrors",
        misconception_tag="ray_passes_through_center_of_curvature",
        attempt=2,
        question_text="Draw the reflected ray for a ray parallel to the principal axis hitting a concave mirror.",
        student_answer="It reflects back through the center of curvature.",
    )
    
    print(f"SVG Component Chosen: {result_dynamic['svg_component']}")
    print("Animation Parameters (Generated by Gemini):")
    print(json.dumps(result_dynamic['animation_parameters'], indent=2))
    print(f"\nExplanation: {result_dynamic['explanation'][:100]}...\n")

if __name__ == "__main__":
    run_tests()
